apiVersion: v1
kind: Secret
metadata:
  name: devicesapi-secret
type: Opaque
data:
  api-key: YOUR_DEVICES_API_KEY_BASE64

---
apiVersion: v1
kind: Secret
metadata:
  name: customersapi-secret
type: Opaque
data:
  api-key: YOUR_CUSTOMERS_API_KEY_BASE64
