apiVersion: apps/v1
kind: Deployment
metadata:
  name: productsapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productsapi
  template:
    metadata:
      labels:
        app: productsapi
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "productsapi"
        dapr.io/app-port: "3000"
    spec:
      containers:
        - name: productsapi
          image: landike/productsapi:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
